"""FindingsStore — encrypted-shard + queryable-index persistence (ADR-0007 §11)."""

from .base import (
    CRITICAL_ENTITIES,
    HIGH_ENTITIES,
    AuditHook,
    EncryptedFinding,
    FindingRecord,
    FindingsStore,
    Severity,
    SeverityClassifier,
    ShardRef,
    Status,
    Verification,
    default_severity,
    derive_finding_id,
    fingerprint_value,
    mask_excerpt,
)
from .encryption import (
    DEK_SIZE,
    NONCE_SIZE,
    TAG_SIZE,
    EncryptedPayload,
    EncryptionError,
    InMemoryKekProvider,
    KekProvider,
    decrypt_payload,
    encrypt_payload,
    generate_dek,
)
from .jsonl_shard import (
    JsonlShardWriter,
    default_shard_base,
    read_shard,
    shard_path,
)
from .memory_store import MemoryFindingsStore
from .sqlite_index import SqliteFindingsStore, default_index_path

__all__ = [
    "CRITICAL_ENTITIES",
    "DEK_SIZE",
    "HIGH_ENTITIES",
    "NONCE_SIZE",
    "TAG_SIZE",
    "AuditHook",
    "EncryptedFinding",
    "EncryptedPayload",
    "EncryptionError",
    "FindingRecord",
    "FindingsStore",
    "InMemoryKekProvider",
    "JsonlShardWriter",
    "KekProvider",
    "MemoryFindingsStore",
    "Severity",
    "SeverityClassifier",
    "ShardRef",
    "SqliteFindingsStore",
    "Status",
    "Verification",
    "decrypt_payload",
    "default_index_path",
    "default_severity",
    "default_shard_base",
    "derive_finding_id",
    "encrypt_payload",
    "fingerprint_value",
    "generate_dek",
    "mask_excerpt",
    "read_shard",
    "shard_path",
]
