apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pii-scanner.fullname" . }}-config
  labels:
    {{- include "pii-scanner.labels" . | nindent 4 }}
data:
  scan.toml: |-
    {{- .Values.scanConfig | nindent 4 }}
