{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pii-scanner.fullname" . }}
  labels:
    {{- include "pii-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.findingsMasterKey }}
  findings-master-key: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubAppPrivateKey }}
  github-app-private-key: {{ . | quote }}
  {{- end }}
{{- end }}
